version: '3.8'

services:
  # Auth Service
  auth-service:
    platform: linux/amd64
    image: 525945693121.dkr.ecr.us-east-1.amazonaws.com/cloudretail-auth-service:prod-v1
    container_name: cloudretail-auth
    ports:
      - "4001:4001"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: cloudretail
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: super_secret_jwt_key
      PORT: 4001
    depends_on:
      - redis

  # Product Service
  product-service:
    platform: linux/amd64
    image: 525945693121.dkr.ecr.us-east-1.amazonaws.com/cloudretail-product-service:prod-v1
    container_name: cloudretail-product
    ports:
      - "4002:4002"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: cloudretail
      JWT_SECRET: super_secret_jwt_key
      PORT: 4002

  # Order Service
  order-service:
    platform: linux/amd64
    image: 525945693121.dkr.ecr.us-east-1.amazonaws.com/cloudretail-order-service:prod-v1
    container_name: cloudretail-order
    ports:
      - "4004:4004"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: cloudretail
      PRODUCT_SERVICE_URL: http://product-service:4002
      JWT_SECRET: super_secret_jwt_key
      PORT: 4004
    depends_on:
      - product-service

  # Inventory Service
  inventory-service:
    platform: linux/amd64
    image: 525945693121.dkr.ecr.us-east-1.amazonaws.com/cloudretail-inventory-service:prod-v1
    container_name: cloudretail-inventory
    ports:
      - "4003:4003"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: cloudretail
      JWT_SECRET: super_secret_jwt_key
      PORT: 4003

  # Gateway Service
  gateway-service:
    platform: linux/amd64
    image: 525945693121.dkr.ecr.us-east-1.amazonaws.com/cloudretail-gateway-service:prod-v1
    container_name: cloudretail-gateway
    ports:
      - "80:4000"
    environment:
      AUTH_SERVICE_URL: http://auth-service:4001
      PRODUCT_SERVICE_URL: http://product-service:4002
      INVENTORY_SERVICE_URL: http://inventory-service:4003
      ORDER_SERVICE_URL: http://order-service:4004
      JWT_SECRET: super_secret_jwt_key
    depends_on:
      - auth-service
      - product-service
      - order-service
      - inventory-service

  # Database Cache Helper (Redis)
  redis:
    image: redis:alpine
    container_name: cloudretail-redis
    ports:
      - "6379:6379"
