version: '3.8'

services:
  # Auth Service
  auth-service:
    image: 525945693121.dkr.ecr.us-east-1.amazonaws.com/cloudretail-auth-service:latest
    container_name: cloudretail-auth
    ports:
      - "4001:4001"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: auth_db
      JWT_SECRET: supersecretkey
      PORT: 4001

  # Product Service
  product-service:
    image: 525945693121.dkr.ecr.us-east-1.amazonaws.com/cloudretail-product-service:latest
    container_name: cloudretail-product
    ports:
      - "4002:4002"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: product_db
      JWT_SECRET: supersecretkey
      PORT: 4002

  # Order Service
  order-service:
    image: 525945693121.dkr.ecr.us-east-1.amazonaws.com/cloudretail-order-service:latest
    container_name: cloudretail-order
    ports:
      - "4004:4004"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: order_db
      PRODUCT_SERVICE_URL: http://product-service:4002
      JWT_SECRET: supersecretkey
      PORT: 4004
    depends_on:
      - product-service

  # Inventory Service
  inventory-service:
    image: 525945693121.dkr.ecr.us-east-1.amazonaws.com/cloudretail-inventory-service:latest
    container_name: cloudretail-inventory
    ports:
      - "4003:4003"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: inventory_db
      JWT_SECRET: supersecretkey
      PORT: 4003

  # Gateway Service
  gateway-service:
    image: 525945693121.dkr.ecr.us-east-1.amazonaws.com/cloudretail-gateway-service:latest
    container_name: cloudretail-gateway
    ports:
      - "4000:4000"
    environment:
      AUTH_SERVICE_URL: http://auth-service:4001
      PRODUCT_SERVICE_URL: http://product-service:4002
      INVENTORY_SERVICE_URL: http://inventory-service:4003
      ORDER_SERVICE_URL: http://order-service:4004
      JWT_SECRET: supersecretkey
    depends_on:
      - auth-service
      - product-service
      - order-service
      - inventory-service

  # Frontend
  frontend:
    image: 525945693121.dkr.ecr.us-east-1.amazonaws.com/cloudretail-frontend:latest
    container_name: cloudretail-frontend
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - product-service
      - order-service
