version: '3.8'

services:
  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: cloudretail-auth
    ports:
      - "4001:4001"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: auth_db
      JWT_SECRET: supersecretkey
      PORT: 4001

  # Product Service
  product-service:
    build: ./product-service
    container_name: cloudretail-product
    ports:
      - "4002:4002"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: product_db
      JWT_SECRET: supersecretkey
      PORT: 4002

  # Order Service
  order-service:
    build: ./order-service
    container_name: cloudretail-order
    ports:
      - "4004:4004"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: order_db
      PRODUCT_SERVICE_URL: http://product-service:4002
      JWT_SECRET: supersecretkey
      PORT: 4004
    depends_on:
      - product-service

  # Inventory Service
  inventory-service:
    build: ./inventory-service
    container_name: cloudretail-inventory
    ports:
      - "4003:4003"
    environment:
      DB_HOST_MAIN: ${RDS_ENDPOINT}
      DB_USER_MAIN: ${RDS_USER}
      DB_PASS_MAIN: ${RDS_PASS}
      DB_NAME_MAIN: inventory_db
      JWT_SECRET: supersecretkey
      PORT: 4003

  # Frontend (Served via simple Nginx or just static files usually, but keeping container if needed)
  frontend:
    build: ./frontend/cloudretail-frontend
    container_name: cloudretail-frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - product-service
      - order-service
