apiVersion: v1
kind: Secret
metadata:
  name: cloudretail-secrets
type: Opaque
stringData:
  DB_PASS_MAIN: "your_password"
  JWT_SECRET: "supersecretkey"
  MYSQL_ROOT_PASSWORD: "your_password"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudretail-config
data:
  DB_HOST_MAIN: "cloudretail-mysql" # Assuming a separate mysql service call or external DB
  DB_PORT_MAIN: "3306"
  DB_USER_MAIN: "root"
  DB_NAME_MAIN: "cloudretail_main"
  AWS_REGION: "us-east-1"
  # Service URLs for internal K8s DNS
  PRODUCT_SERVICE_URL: "http://product-service"
  ORDER_SERVICE_URL: "http://order-service"
  AUTH_SERVICE_URL: "http://auth-service"
  INVENTORY_SERVICE_URL: "http://inventory-service"
