apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudretail-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 4001
      - path: /api/v1/products
        pathType: Prefix
        backend:
          service:
            name: product-service
            port:
              number: 4002
      - path: /api/v1/orders
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 4004
      - path: /api/v1/cart
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 4004
            name: frontend
            port:
              number: 80
  # TLS Configuration
  # This requires a Kubernetes Secret named "cloudretail-tls" containing tls.crt and tls.key
  tls:
  - hosts:
    - cloudretail.local
    secretName: cloudretail-tls
